[package]
name = "rust-ml-first"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
matrix = {path = "../matrix"}
serde = { version = "1.0.198", features = ["derive"] }
serde_json = "1.0.116"
